# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'Boxes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'gRPC-Swift', '1.0.0-alpha.12'
  # Pods for Boxes

  target 'BoxesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
