# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boxes.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='boxes.proto',
  package='boxes',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x62oxes.proto\x12\x05\x62oxes\"\x07\n\x05\x45mpty\"\x19\n\tTableName\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\nTableNames\x12\x13\n\x0btable_names\x18\x01 \x03(\t\"9\n\x0cTableSchemas\x12)\n\rtable_schemas\x18\x01 \x03(\x0b\x32\x12.boxes.TableSchema\":\n\x0bTableSchema\x12+\n\x0e\x63olumn_schemas\x18\x01 \x03(\x0b\x32\x13.boxes.ColumnSchema\"=\n\x0c\x43olumnSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.boxes.ColumnType\"-\n\x05Table\x12$\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x13.boxes.ColumnValues\"6\n\x0c\x43olumnValues\x12\x12\n\nstr_values\x18\x01 \x03(\t\x12\x12\n\nnum_values\x18\x02 \x03(\x01\"\x1c\n\nDoubleList\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1c\n\x0b\x44oubleValue\x12\r\n\x05value\x18\x01 \x01(\x01\";\n\x05Query\x12\t\n\x01q\x18\x01 \x01(\t\x12\'\n\x0c\x63olumn_types\x18\x02 \x03(\x0e\x32\x11.boxes.ColumnType*G\n\nColumnType\x12\n\n\x06UNUSED\x10\x00\x12\x0b\n\x07INTEGER\x10\x01\x12\x08\n\x04REAL\x10\x02\x12\x08\n\x04TEXT\x10\x03\x12\x0c\n\x08\x44\x41TETIME\x10\x04\x32\xaa\x01\n\tConnector\x12\x32\n\rGetTableNames\x12\x0c.boxes.Empty\x1a\x11.boxes.TableNames\"\x00\x12;\n\x0fGetTableSchemas\x12\x11.boxes.TableNames\x1a\x13.boxes.TableSchemas\"\x00\x12,\n\x08GetTable\x12\x10.boxes.TableName\x1a\x0c.boxes.Table\"\x00\x32\xd3\x01\n\nAlgorithms\x12.\n\x03Max\x12\x11.boxes.DoubleList\x1a\x12.boxes.DoubleValue\"\x00\x12.\n\x03Min\x12\x11.boxes.DoubleList\x1a\x12.boxes.DoubleValue\"\x00\x12\x32\n\x07\x41verage\x12\x11.boxes.DoubleList\x1a\x12.boxes.DoubleValue\"\x00\x12\x31\n\x06Median\x12\x11.boxes.DoubleList\x1a\x12.boxes.DoubleValue\"\x00\x32:\n\nDataEngine\x12,\n\x0c\x45xecuteQuery\x12\x0c.boxes.Query\x1a\x0c.boxes.Table\"\x00\x62\x06proto3'
)

_COLUMNTYPE = _descriptor.EnumDescriptor(
  name='ColumnType',
  full_name='boxes.ColumnType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTEGER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATETIME', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=499,
  serialized_end=570,
)
_sym_db.RegisterEnumDescriptor(_COLUMNTYPE)

ColumnType = enum_type_wrapper.EnumTypeWrapper(_COLUMNTYPE)
UNUSED = 0
INTEGER = 1
REAL = 2
TEXT = 3
DATETIME = 4



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='boxes.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=29,
)


_TABLENAME = _descriptor.Descriptor(
  name='TableName',
  full_name='boxes.TableName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='boxes.TableName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=56,
)


_TABLENAMES = _descriptor.Descriptor(
  name='TableNames',
  full_name='boxes.TableNames',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_names', full_name='boxes.TableNames.table_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=91,
)


_TABLESCHEMAS = _descriptor.Descriptor(
  name='TableSchemas',
  full_name='boxes.TableSchemas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_schemas', full_name='boxes.TableSchemas.table_schemas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=150,
)


_TABLESCHEMA = _descriptor.Descriptor(
  name='TableSchema',
  full_name='boxes.TableSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_schemas', full_name='boxes.TableSchema.column_schemas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=210,
)


_COLUMNSCHEMA = _descriptor.Descriptor(
  name='ColumnSchema',
  full_name='boxes.ColumnSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='boxes.ColumnSchema.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='boxes.ColumnSchema.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=273,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='boxes.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='boxes.Table.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=320,
)


_COLUMNVALUES = _descriptor.Descriptor(
  name='ColumnValues',
  full_name='boxes.ColumnValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_values', full_name='boxes.ColumnValues.str_values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_values', full_name='boxes.ColumnValues.num_values', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=376,
)


_DOUBLELIST = _descriptor.Descriptor(
  name='DoubleList',
  full_name='boxes.DoubleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='boxes.DoubleList.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=406,
)


_DOUBLEVALUE = _descriptor.Descriptor(
  name='DoubleValue',
  full_name='boxes.DoubleValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='boxes.DoubleValue.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=436,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='boxes.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='q', full_name='boxes.Query.q', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_types', full_name='boxes.Query.column_types', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=497,
)

_TABLESCHEMAS.fields_by_name['table_schemas'].message_type = _TABLESCHEMA
_TABLESCHEMA.fields_by_name['column_schemas'].message_type = _COLUMNSCHEMA
_COLUMNSCHEMA.fields_by_name['type'].enum_type = _COLUMNTYPE
_TABLE.fields_by_name['columns'].message_type = _COLUMNVALUES
_QUERY.fields_by_name['column_types'].enum_type = _COLUMNTYPE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TableName'] = _TABLENAME
DESCRIPTOR.message_types_by_name['TableNames'] = _TABLENAMES
DESCRIPTOR.message_types_by_name['TableSchemas'] = _TABLESCHEMAS
DESCRIPTOR.message_types_by_name['TableSchema'] = _TABLESCHEMA
DESCRIPTOR.message_types_by_name['ColumnSchema'] = _COLUMNSCHEMA
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['ColumnValues'] = _COLUMNVALUES
DESCRIPTOR.message_types_by_name['DoubleList'] = _DOUBLELIST
DESCRIPTOR.message_types_by_name['DoubleValue'] = _DOUBLEVALUE
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.enum_types_by_name['ColumnType'] = _COLUMNTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.Empty)
  })
_sym_db.RegisterMessage(Empty)

TableName = _reflection.GeneratedProtocolMessageType('TableName', (_message.Message,), {
  'DESCRIPTOR' : _TABLENAME,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.TableName)
  })
_sym_db.RegisterMessage(TableName)

TableNames = _reflection.GeneratedProtocolMessageType('TableNames', (_message.Message,), {
  'DESCRIPTOR' : _TABLENAMES,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.TableNames)
  })
_sym_db.RegisterMessage(TableNames)

TableSchemas = _reflection.GeneratedProtocolMessageType('TableSchemas', (_message.Message,), {
  'DESCRIPTOR' : _TABLESCHEMAS,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.TableSchemas)
  })
_sym_db.RegisterMessage(TableSchemas)

TableSchema = _reflection.GeneratedProtocolMessageType('TableSchema', (_message.Message,), {
  'DESCRIPTOR' : _TABLESCHEMA,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.TableSchema)
  })
_sym_db.RegisterMessage(TableSchema)

ColumnSchema = _reflection.GeneratedProtocolMessageType('ColumnSchema', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNSCHEMA,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.ColumnSchema)
  })
_sym_db.RegisterMessage(ColumnSchema)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), {
  'DESCRIPTOR' : _TABLE,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.Table)
  })
_sym_db.RegisterMessage(Table)

ColumnValues = _reflection.GeneratedProtocolMessageType('ColumnValues', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNVALUES,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.ColumnValues)
  })
_sym_db.RegisterMessage(ColumnValues)

DoubleList = _reflection.GeneratedProtocolMessageType('DoubleList', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLELIST,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.DoubleList)
  })
_sym_db.RegisterMessage(DoubleList)

DoubleValue = _reflection.GeneratedProtocolMessageType('DoubleValue', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEVALUE,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.DoubleValue)
  })
_sym_db.RegisterMessage(DoubleValue)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'boxes_pb2'
  # @@protoc_insertion_point(class_scope:boxes.Query)
  })
_sym_db.RegisterMessage(Query)



_CONNECTOR = _descriptor.ServiceDescriptor(
  name='Connector',
  full_name='boxes.Connector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=573,
  serialized_end=743,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTableNames',
    full_name='boxes.Connector.GetTableNames',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TABLENAMES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTableSchemas',
    full_name='boxes.Connector.GetTableSchemas',
    index=1,
    containing_service=None,
    input_type=_TABLENAMES,
    output_type=_TABLESCHEMAS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTable',
    full_name='boxes.Connector.GetTable',
    index=2,
    containing_service=None,
    input_type=_TABLENAME,
    output_type=_TABLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTOR)

DESCRIPTOR.services_by_name['Connector'] = _CONNECTOR


_ALGORITHMS = _descriptor.ServiceDescriptor(
  name='Algorithms',
  full_name='boxes.Algorithms',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=746,
  serialized_end=957,
  methods=[
  _descriptor.MethodDescriptor(
    name='Max',
    full_name='boxes.Algorithms.Max',
    index=0,
    containing_service=None,
    input_type=_DOUBLELIST,
    output_type=_DOUBLEVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Min',
    full_name='boxes.Algorithms.Min',
    index=1,
    containing_service=None,
    input_type=_DOUBLELIST,
    output_type=_DOUBLEVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Average',
    full_name='boxes.Algorithms.Average',
    index=2,
    containing_service=None,
    input_type=_DOUBLELIST,
    output_type=_DOUBLEVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Median',
    full_name='boxes.Algorithms.Median',
    index=3,
    containing_service=None,
    input_type=_DOUBLELIST,
    output_type=_DOUBLEVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALGORITHMS)

DESCRIPTOR.services_by_name['Algorithms'] = _ALGORITHMS


_DATAENGINE = _descriptor.ServiceDescriptor(
  name='DataEngine',
  full_name='boxes.DataEngine',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=959,
  serialized_end=1017,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecuteQuery',
    full_name='boxes.DataEngine.ExecuteQuery',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_TABLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAENGINE)

DESCRIPTOR.services_by_name['DataEngine'] = _DATAENGINE

# @@protoc_insertion_point(module_scope)
