# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from common import boxes_pb2 as boxes__pb2


class ConnectorStub(object):
    """---------------------------------------------------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTableNames = channel.unary_unary(
                '/boxes.Connector/GetTableNames',
                request_serializer=boxes__pb2.Empty.SerializeToString,
                response_deserializer=boxes__pb2.TableNames.FromString,
                )
        self.GetTableSchemas = channel.unary_unary(
                '/boxes.Connector/GetTableSchemas',
                request_serializer=boxes__pb2.TableNames.SerializeToString,
                response_deserializer=boxes__pb2.TableSchemas.FromString,
                )
        self.GetTable = channel.unary_unary(
                '/boxes.Connector/GetTable',
                request_serializer=boxes__pb2.TableName.SerializeToString,
                response_deserializer=boxes__pb2.Table.FromString,
                )


class ConnectorServicer(object):
    """---------------------------------------------------------------------------------------------------------------------

    """

    def GetTableNames(self, request, context):
        """Get table schemas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTableSchemas(self, request, context):
        """Get table schemas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTable(self, request, context):
        """Get table contents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTableNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTableNames,
                    request_deserializer=boxes__pb2.Empty.FromString,
                    response_serializer=boxes__pb2.TableNames.SerializeToString,
            ),
            'GetTableSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTableSchemas,
                    request_deserializer=boxes__pb2.TableNames.FromString,
                    response_serializer=boxes__pb2.TableSchemas.SerializeToString,
            ),
            'GetTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTable,
                    request_deserializer=boxes__pb2.TableName.FromString,
                    response_serializer=boxes__pb2.Table.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boxes.Connector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connector(object):
    """---------------------------------------------------------------------------------------------------------------------

    """

    @staticmethod
    def GetTableNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Connector/GetTableNames',
            boxes__pb2.Empty.SerializeToString,
            boxes__pb2.TableNames.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTableSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Connector/GetTableSchemas',
            boxes__pb2.TableNames.SerializeToString,
            boxes__pb2.TableSchemas.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Connector/GetTable',
            boxes__pb2.TableName.SerializeToString,
            boxes__pb2.Table.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class AlgorithmsStub(object):
    """---------------------------------------------------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Max = channel.unary_unary(
                '/boxes.Algorithms/Max',
                request_serializer=boxes__pb2.DoubleList.SerializeToString,
                response_deserializer=boxes__pb2.DoubleValue.FromString,
                )
        self.Min = channel.unary_unary(
                '/boxes.Algorithms/Min',
                request_serializer=boxes__pb2.DoubleList.SerializeToString,
                response_deserializer=boxes__pb2.DoubleValue.FromString,
                )
        self.Average = channel.unary_unary(
                '/boxes.Algorithms/Average',
                request_serializer=boxes__pb2.DoubleList.SerializeToString,
                response_deserializer=boxes__pb2.DoubleValue.FromString,
                )
        self.Median = channel.unary_unary(
                '/boxes.Algorithms/Median',
                request_serializer=boxes__pb2.DoubleList.SerializeToString,
                response_deserializer=boxes__pb2.DoubleValue.FromString,
                )


class AlgorithmsServicer(object):
    """---------------------------------------------------------------------------------------------------------------------

    """

    def Max(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Min(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Average(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Median(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Max': grpc.unary_unary_rpc_method_handler(
                    servicer.Max,
                    request_deserializer=boxes__pb2.DoubleList.FromString,
                    response_serializer=boxes__pb2.DoubleValue.SerializeToString,
            ),
            'Min': grpc.unary_unary_rpc_method_handler(
                    servicer.Min,
                    request_deserializer=boxes__pb2.DoubleList.FromString,
                    response_serializer=boxes__pb2.DoubleValue.SerializeToString,
            ),
            'Average': grpc.unary_unary_rpc_method_handler(
                    servicer.Average,
                    request_deserializer=boxes__pb2.DoubleList.FromString,
                    response_serializer=boxes__pb2.DoubleValue.SerializeToString,
            ),
            'Median': grpc.unary_unary_rpc_method_handler(
                    servicer.Median,
                    request_deserializer=boxes__pb2.DoubleList.FromString,
                    response_serializer=boxes__pb2.DoubleValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boxes.Algorithms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Algorithms(object):
    """---------------------------------------------------------------------------------------------------------------------

    """

    @staticmethod
    def Max(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Algorithms/Max',
            boxes__pb2.DoubleList.SerializeToString,
            boxes__pb2.DoubleValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Min(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Algorithms/Min',
            boxes__pb2.DoubleList.SerializeToString,
            boxes__pb2.DoubleValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Average(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Algorithms/Average',
            boxes__pb2.DoubleList.SerializeToString,
            boxes__pb2.DoubleValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Median(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.Algorithms/Median',
            boxes__pb2.DoubleList.SerializeToString,
            boxes__pb2.DoubleValue.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class DataEngineStub(object):
    """---------------------------------------------------------------------------------------------------------------------


    Data engine känner till alla tabeller i alla connectorer
    Den håller en tabell med alla tabeller och huruvida de är laddade eller ej
    Den laddar tabeller till en sqlite in memory databas vid behov, mha namnkonvention borde vi kunna hitta tabeller i queries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
                '/boxes.DataEngine/ExecuteQuery',
                request_serializer=boxes__pb2.Query.SerializeToString,
                response_deserializer=boxes__pb2.Table.FromString,
                )


class DataEngineServicer(object):
    """---------------------------------------------------------------------------------------------------------------------


    Data engine känner till alla tabeller i alla connectorer
    Den håller en tabell med alla tabeller och huruvida de är laddade eller ej
    Den laddar tabeller till en sqlite in memory databas vid behov, mha namnkonvention borde vi kunna hitta tabeller i queries
    """

    def ExecuteQuery(self, request, context):
        """Plot x antal axlar
        Axel kategorisk eller numerisk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=boxes__pb2.Query.FromString,
                    response_serializer=boxes__pb2.Table.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boxes.DataEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataEngine(object):
    """---------------------------------------------------------------------------------------------------------------------


    Data engine känner till alla tabeller i alla connectorer
    Den håller en tabell med alla tabeller och huruvida de är laddade eller ej
    Den laddar tabeller till en sqlite in memory databas vid behov, mha namnkonvention borde vi kunna hitta tabeller i queries
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/boxes.DataEngine/ExecuteQuery',
            boxes__pb2.Query.SerializeToString,
            boxes__pb2.Table.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
