# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='table.proto',
  package='tableservices',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0btable.proto\x12\rtableservices\"\x15\n\x05Query\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05Table\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\nTableQuery\x12\x38\n\x08GetTable\x12\x14.tableservices.Query\x1a\x14.tableservices.Table\"\x00\x62\x06proto3'
)




_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='tableservices.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tableservices.Query.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=51,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='tableservices.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tableservices.Table.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'table_pb2'
  # @@protoc_insertion_point(class_scope:tableservices.Query)
  })
_sym_db.RegisterMessage(Query)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), {
  'DESCRIPTOR' : _TABLE,
  '__module__' : 'table_pb2'
  # @@protoc_insertion_point(class_scope:tableservices.Table)
  })
_sym_db.RegisterMessage(Table)



_TABLEQUERY = _descriptor.ServiceDescriptor(
  name='TableQuery',
  full_name='tableservices.TableQuery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTable',
    full_name='tableservices.TableQuery.GetTable',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_TABLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TABLEQUERY)

DESCRIPTOR.services_by_name['TableQuery'] = _TABLEQUERY

# @@protoc_insertion_point(module_scope)
