# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='table.proto',
  package='tableservices',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0btable.proto\x12\rtableservices\"\x19\n\x06\x41nswer\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x15\n\x05Query\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x05Table\x12&\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x15.tableservices.Column\"g\n\x06\x43olumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.tableservices.ColumnType\x12\x12\n\nstr_values\x18\x03 \x03(\t\x12\x12\n\ndec_values\x18\x04 \x03(\x01*1\n\nColumnType\x12\n\n\x06UNUSED\x10\x00\x12\x0b\n\x07\x44\x45\x43IMAL\x10\x01\x12\n\n\x06STRING\x10\x02\x32\x46\n\nTableQuery\x12\x38\n\x08GetTable\x12\x14.tableservices.Query\x1a\x14.tableservices.Table\"\x00\x32\x46\n\nAlgorithms\x12\x38\n\x07\x41verage\x12\x14.tableservices.Query\x1a\x15.tableservices.Answer\"\x00\x62\x06proto3'
)

_COLUMNTYPE = _descriptor.EnumDescriptor(
  name='ColumnType',
  full_name='tableservices.ColumnType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECIMAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=234,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_COLUMNTYPE)

ColumnType = enum_type_wrapper.EnumTypeWrapper(_COLUMNTYPE)
UNUSED = 0
DECIMAL = 1
STRING = 2



_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='tableservices.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tableservices.Answer.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=55,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='tableservices.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tableservices.Query.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=78,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='tableservices.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='tableservices.Table.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=127,
)


_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='tableservices.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tableservices.Column.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tableservices.Column.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_values', full_name='tableservices.Column.str_values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dec_values', full_name='tableservices.Column.dec_values', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=232,
)

_TABLE.fields_by_name['columns'].message_type = _COLUMN
_COLUMN.fields_by_name['type'].enum_type = _COLUMNTYPE
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.enum_types_by_name['ColumnType'] = _COLUMNTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'table_pb2'
  # @@protoc_insertion_point(class_scope:tableservices.Answer)
  })
_sym_db.RegisterMessage(Answer)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'table_pb2'
  # @@protoc_insertion_point(class_scope:tableservices.Query)
  })
_sym_db.RegisterMessage(Query)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), {
  'DESCRIPTOR' : _TABLE,
  '__module__' : 'table_pb2'
  # @@protoc_insertion_point(class_scope:tableservices.Table)
  })
_sym_db.RegisterMessage(Table)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), {
  'DESCRIPTOR' : _COLUMN,
  '__module__' : 'table_pb2'
  # @@protoc_insertion_point(class_scope:tableservices.Column)
  })
_sym_db.RegisterMessage(Column)



_TABLEQUERY = _descriptor.ServiceDescriptor(
  name='TableQuery',
  full_name='tableservices.TableQuery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=285,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTable',
    full_name='tableservices.TableQuery.GetTable',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_TABLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TABLEQUERY)

DESCRIPTOR.services_by_name['TableQuery'] = _TABLEQUERY


_ALGORITHMS = _descriptor.ServiceDescriptor(
  name='Algorithms',
  full_name='tableservices.Algorithms',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=357,
  serialized_end=427,
  methods=[
  _descriptor.MethodDescriptor(
    name='Average',
    full_name='tableservices.Algorithms.Average',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_ANSWER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALGORITHMS)

DESCRIPTOR.services_by_name['Algorithms'] = _ALGORITHMS

# @@protoc_insertion_point(module_scope)
